
import { type NextPage } from "next";
import Head from "next/head";
//import { signIn, signOut, useSession } from "next-auth/react";
//import { api } from "askov/utils/api";

//import { Navbar } from "../components/Navbar";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Askov</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <Navbar />
    </main>
    </>
  );
};

export default Home;
