
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Askov</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="hero min-h-screen bg-[url('/Hjemmet.JPG')]"  >
            <div className="hero-overlay bg-opacity-60"></div>
            <div className="hero-content text-center text-neutral-content">
              <div className="max-w-md">
                <h1 className="mb-5 text-5xl font-bold">Velkommen til familien askov</h1>
                <p className="mb-5">Denne hjemmeside er stadig under udvikling, kom gerne med feedback hvis der er noget de synes der skal opdaters. Du kan skrive til min mail hans@askov.dk</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
